export type UserRole = 'omc' | 'customer' | 'driver';

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  phone?: string;
  companyName?: string;  // for customers & OMC
  customerId?: string;   // for drivers linking them to a customer/company
}

export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  companyName: string;
  address?: string;
  createdAt: string;
}

export interface Driver {
  id: string;
  name: string;
  phone: string;
  email?: string;
  customerId: string;
  nrc?: string;
  nationality?: string;
  userId?: string;       // Link to User account allowing driver to log in
}

export interface Vehicle {
  id: string;
  regNumber: string;
  type: VehicleType;
  tankCapacity: number;
  customerId: string;
  assignedDriverId?: string;  // Which driver is assigned this vehicle
}

export type VehicleType =
  | 'Sedan'
  | 'SUV'
  | 'Truck'
  | 'Bus'
  | 'Motorcycle'
  | 'Van'
  | 'Tanker'
  | 'Pickup'
  | 'Other';

export type FuelType = 'Petrol' | 'Diesel';

export type OrderStatus =
  | 'draft'
  | 'sent'
  | 'pending'
  | 'approved'
  | 'rejected'
  | 'dispensing'
  | 'completed';

export interface FuelOrder {
  id: string;
  customerId: string;
  customerName: string;
  siteId: string;
  driverId: string;
  driverName: string;
  driverPhone: string;
  vehicleId: string;
  vehicleRegNumber: string;
  vehicleType: VehicleType | string;
  tankCapacity: number;       // in litres
  fuelVolumeAllocated: number; // in litres (requested_fuel in backend)
  fuelType: FuelType;
  otp?: string;               // Generated by driver via API
  otpExpiresAt?: string;      // OTP expiration time
  otpActive: boolean;
  status: OrderStatus;
  createdAt: string;
  approvedAt?: string;
  approvedBy?: string;
  rejectionReason?: string;
  completedAt?: string;
}

export interface NewOrderFormData {
  siteId: string;
  driverId: string;
  vehicleId: string;
  fuelVolumeAllocated: number;
  fuelType: FuelType;
}

export interface Site {
  id: string;
  name: string;
  address: string;
}
